# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

#pool:
#vmImage: ubuntu-latest
pool:
  name: Default #Testing with self-hosted agent


steps:
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'web_app-connection'
      appType: 'webApp'
      appName: 'rajeshwarwebapp'
      package: '$(System.DefaultWorkingDirectory)/*.zip'
      deploymentMethod: 'auto'